/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _DT_BINDINGS_LEDS_QCOM_SPMI_FLASH_H
#define _DT_BINDINGS_LEDS_QCOM_SPMI_FLASH_H

#define QCOM_SPMI_FLASH_HEADROOM_250MV	0
#define QCOM_SPMI_FLASH_HEADROOM_300MV	1
#define QCOM_SPMI_FLASH_HEADROOM_400MV	2
#define QCOM_SPMI_FLASH_HEADROOM_500MV	3

#define QCOM_SPMI_FLASH_STARTUP_DLY_10US	0
#define QCOM_SPMI_FLASH_STARTUP_DLY_32US	1
#define QCOM_SPMI_FLASH_STARTUP_DLY_64US	2
#define QCOM_SPMI_FLASH_STARTUP_DLY_128US	3

#endif
